version: "2"
services:
    service-a:
        image: localhost:5000/sample-app/service-a
        environment:
            - APPINSIGHTS_INSTRUMENTATIONKEY
        ports:
            - "8080:80"
        links:
            - service-b
    
    service-b:
        image: localhost:5000/sample-app/service-b:v0.1.0
        environment:
            - APPINSIGHTS_INSTRUMENTATIONKEY
        expose:
            - 80
    
    redis:
        image: redis:latest
        expose:
            - 6379
