version: "2"
services:
    service-a:
        image: # TODO
        environment:
            - APPINSIGHTS_INSTRUMENTATIONKEY
        ports:
            - "8080:80"
        links:
            - service-b
    
    service-b:
        image: # TODO
        environment:
            - APPINSIGHTS_INSTRUMENTATIONKEY
        expose:
            - 80